### ISSUE TITLE
Error: size mismatch

### ISSUE THREAD

**Issue by RusTorg** [lihaibh/mongodb-snapshot#15] opened 2020-12-26 17:12 UTC
I'm trying to dump from mongo to tar, scripts work 3-4 minutes and throw error

last log
```bash
...
14|backup_task  | remaining bytes to write: 246657495
14|backup_task  | remaining bytes to write: 246657286
14|backup_task  | remaining bytes to write: 246657077
14|backup_task  | remaining bytes to write: 246656868
14|backup_task  | remaining bytes to write: 246656659
14|backup_task  | remaining bytes to write: 246656450
14|backup_task  | remaining bytes to write: 246656241
14|backup_task  | remaining bytes to write: 246656032
14|backup_task  | remaining bytes to write: 246655823
14|backup_task  | remaining bytes to write: 246655614
14|backup_task  | could not write collection data into: type: local, path: ./mongo.tar due to error:
14|backup_task  | Error: size mismatch
14|backup_task  |     at Sink.<anonymous> (/srv/backup/node_modules/tar-stream/pack.js:175:23)
14|backup_task  |     at Sink.f (/srv/backup/node_modules/once/once.js:25:25)
14|backup_task  |     at Sink.onfinish (/srv/backup/node_modules/end-of-stream/index.js:31:27)
14|backup_task  |     at Sink.emit (events.js:315:20)
14|backup_task  |     at finishMaybe (/srv/backup/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:624:14)
14|backup_task  |     at endWritable (/srv/backup/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:643:3)
14|backup_task  |     at Sink.Writable.end (/srv/backup/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_writable.js:571:22)
14|backup_task  |     at SafeSubscriber._complete (/srv/backup/node_modules/mongodb-snapshot/dist/connectors/filesystem/FileSystemDuplexConnector.js:273:19)
14|backup_task  |     at SafeSubscriber.wrappedComplete (/srv/backup/node_modules/rxjs/internal/Subscriber.js:190:76)
14|backup_task  |     at SafeSubscriber.__tryOrUnsub (/srv/backup/node_modules/rxjs/internal/Subscriber.js:207:16)
14|backup_task  | removing: "type: local, path: ./mongo.tar" because an error was thrown during the transfer
```

used code

```javascript
async function dumpMongo2Localfile() {
    console.log(`mongo bk -- start`);
    const mongo_connector = new MongoDBDuplexConnector({
        connection: {
            uri: `mongodb://localhost`,
            dbname: 'geoip',
        },
    });

    const localfile_connector = new LocalFileSystemDuplexConnector({
        connection: {
            path: './mongo.tar',
        },
    });

    const transferer = new MongoTransferer({
        source: mongo_connector,
        targets: [localfile_connector],
    });

    for await (const { total, write } of transferer) {
       console.log(`remaining bytes to write: ${total - write}`);
    }

    console.log(`mongo bk -- done`);
}
```

npm package version

```json
"mongodb-snapshot": "^1.2.1"
```

node version

```bash
root@cs553573:/srv/backup# node -v
v14.1.0
```

mongodb version

```bash
root@cs553573:/srv/backup# mongod --version
db version v4.2.5
git version: 2261279b51ea13df08ae708ff278f0679c59dc32
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1804
    distarch: x86_64
    target_arch: x86_64
```

db stats

```json
  {
    "avgObjSize": 253.81038799023667707,
    "collections": 8,
    "dataSize": 332441100,
    "db": "geoip",
    "fsTotalSize": 63345287168,
    "fsUsedSize": 45903093760,
    "indexSize": 135430144,
    "indexes": 13,
    "numExtents": 0,
    "objects": 1309801,
    "ok": 1,
    "scaleFactor": 1,
    "storageSize": 345493504,
    "views": 0
  }
```

on another project this code work perfectly

**Comment by lihaibh** [comment] 2020-12-26 18:02
@RusTorg this error occurs when the size of a collection is not the same as the size of the data itself.
The library currently need to know the file size inside the result tar file before writing into it.
What happens actually is that you are getting a stream of collection data that is bigger than the size that was declared.
can you find what collection is problematic?

you can use the `collections` property inside the "source" object.
Try to run it multiple times to see if it is consistent.

**Comment by lihaibh** [comment] 2021-01-04 08:32
@RusTorg can you give an update?

**Comment by paulbraam** [comment] 2021-02-20 09:24
Hi @RusTorg 

I'm getting this issue, too

```
could not write collection data into: type: local, path: ./backup/2021-02-20.tar due to error:
Error: size mismatch
    at Sink.<anonymous> (C:\Users\pavel\Desktop\botdev\bot\node_modules\tar-stream\pack.js:175:23)
    at Sink.f (C:\Users\pavel\Desktop\botdev\bot\node_modules\once\once.js:25:25)
    at Sink.onfinish (C:\Users\pavel\Desktop\botdev\bot\node_modules\end-of-stream\index.js:31:27)
    at Sink.emit (events.js:223:5)
    at finishMaybe (C:\Users\pavel\Desktop\botdev\bot\node_modules\readable-stream\lib\_stream_writable.js:624:14)
    at endWritable (C:\Users\pavel\Desktop\botdev\bot\node_modules\readable-stream\lib\_stream_writable.js:643:3)
    at Sink.Writable.end (C:\Users\pavel\Desktop\botdev\bot\node_modules\readable-stream\lib\_stream_writable.js:571:22)
    at SafeSubscriber._error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\dist\connectors\filesystem\FileSystemDuplexConnector.js:271:19)
    at SafeSubscriber.__tryOrUnsub (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:207:16)
    at SafeSubscriber.error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:158:26)
    at Subscriber._error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MergeMapSubscriber.Subscriber._error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MergeMapSubscriber.Subscriber.error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MergeMapSubscriber.OuterSubscriber.notifyError (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\OuterSubscriber.js:26:26)
    at InnerSubscriber._error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\InnerSubscriber.js:31:21)
    at InnerSubscriber.Subscriber.error (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\node_modules\rxjs\internal\Subscriber.js:72:18)
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb-snapshot\dist\connectors\MongoDBDuplexConnector.js:472:26
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\cursor.js:741:11
    at handleCallback (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\utils.js:102:55)
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\operations\cursor_ops.js:97:23
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\utils.js:684:9
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\cursor.js:250:25
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\core\cursor.js:739:9
    at done (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\core\cursor.js:461:7)
    at C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\core\cursor.js:536:11
    at executeCallback (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\operations\execute_operation.js:70:5)
    at callbackWithRetry (C:\Users\pavel\Desktop\botdev\bot\node_modules\mongodb\lib\operations\execute_operation.js:122:14)
removing: "type: local, path: ./backup/2021-02-20.tar" because an error was thrown during the transfer
```

The solution above doesn't work either


``` javascript
const transferer = new MongoTransferer({
      source: {
        collections: ['users']
      },
      targets: [mongo_connector],
  });
```

Please suggest how to workaround this. Thanks.

**Comment by lihaibh** [comment] 2021-02-22 16:40
@paulbraam can you please give me the metadata of this collection?
you can do it by simply run:
```
db.getCollection('users').stats()
```

The problem is that for some reason the size of the collection as we get from the collection metadata is not the right size.
so if we try to write more data (in bytes) than the size of the collection you will have this error.

I can do a workaround fix for that by just cutting the stream of bytes to be exactly the size of the collection, but i dont think it is the right way of solving this issue.

**Comment by bakdakonusuruz** [comment] 2021-03-15 20:14
Hi there,
I'm having the same issue when I first time tried to use it. I just have a test log db and just one collection in it. But it's in the Mongo Atlas Cluster, is it affecting in any way?

`
{
    "ns" : "teco-logs.activityLogs",
    "size" : 60134493,
    "count" : 43743,
    "avgObjSize" : 1374,
    "storageSize" : 9199616,
    "freeStorageSize" : 225280,
    "capped" : false,
    "nindexes" : 1,
    "indexBuilds" : [],
    "totalIndexSize" : 638976,
    "totalSize" : 9838592,
    "indexSizes" : {
        "_id_" : 638976
    },
    "scaleFactor" : 1,
    "ok" : 1.0,
    "$clusterTime" : {
        "clusterTime" : Timestamp(1615838803, 2),
        "signature" : {
            "hash" : { "$binary" : "ZvVwzTQasfaf", "$type" : "00" },
            "keyId" : NumberLong(6891674505635168258)
        }
    },
    "operationTime" : Timestamp(1615838803, 2)
}
`

**Comment by lihaibh** [comment] 2021-03-16 14:02
@bakdakonusuruz @BradGamez maybe the collection modified during the transfer? is it possible? or the problem is consistent even if you try to perform the backup multiple times?
i just want to understand the core of the problem.
I managed to reproduce the error only when i added more documents to a collection during its backup.

**Comment by bakdakonusuruz** [comment] 2021-03-16 14:07
@lihaibh I think the same thing. I added a document while I was trying to backup my local mongo instance and it gave the same error. So, it confirms your assumption.

But still not working on Atlas clusters. My Atlas Cluster is just a test DB and I'm pretty sure that I'm not modifying any document in Atlas Cluster.

**Comment by BradGamez** [comment] 2021-03-16 14:40
> @bakdakonusuruz @BradGamez maybe the collection modified during the transfer? is it possible? or the problem is consistent even if you try to perform the backup multiple times?
> i just want to understand the core of the problem.
> I managed to reproduce the error only when i added more documents to a collection during its backup.

The backup has tried to run every day since 2/17/2021 at 5am. However, is it very likely the collection is being modified during the transfer now that you mention it because it is a live database serving ~ 450,000 users. Is there a way around that since it is most likely that causing it?

**Comment by lihaibh** [comment] 2021-03-16 15:03
@bakdakonusuruz @BradGamez I don't want to lock the database obviously so the only workaround for this problem is cutting out the extra data without backup it.

**Comment by BradGamez** [comment] 2021-03-16 15:05
@lihaibh Sounds like a great option for my use case. How could I make that happen?

**Comment by lihaibh** [comment] 2021-03-16 15:07
@BradGamez im working on a fix now

**Comment by BradGamez** [comment] 2021-03-29 04:41
Any updates on the fix?

**Comment by lihaibh** [comment] 2021-03-30 15:07
@BradGamez @bakdakonusuruz @paulbraam i made some changes and local testing, ive released this version: 1.2.2-rc.0 so please update your package.json file and ping me if everything is ok so i can close the branch.

**Comment by lihaibh** [comment] 2021-03-31 08:46
@BradGamez any update?

**Comment by lihaibh** [comment] 2021-03-31 17:29
@bakdakonusuruz @paulbraam can you please check this i think it solves the problem but i want to verify it before i release official version.
Thanks.

**Comment by paulbraam** [comment] 2021-04-05 20:17
Hi @lihaibh
I will check it and let you know asap.

**Comment by arghyac35** [comment] 2021-04-07 04:20
> `1.2.2-rc.0` so please update your `package.json`

How do I update it to this version? as it is not released in npm so it gives an error.

Also, I tried to change package.json like this:
`"mongodb-snapshot": "lihaibh/mongodb-snapshot#v1.2.2-rc.0",`
yarn cloud build it, but in code, it shows:
`Cannot find module 'mongodb-snapshot' or its corresponding type declarations.`

Can you please say what I am doing wrong?

**Comment by lihaibh** [comment] 2021-04-07 10:59
@arghyac35 you right, i didnt notice that the previous publish failed. You can try now

**Comment by arghyac35** [comment] 2021-04-07 11:14
@lihaibh I tried it just now, unfortunately the error is still there:
![image](https://user-images.githubusercontent.com/27964664/113857715-79541280-97c0-11eb-9bc0-cd40d3c20a81.png)

**Comment by lihaibh** [comment] 2021-04-07 14:18
@arghyac35 can you make sure in package.lock that you are using the right version? 1.2.2-rc.0

**Comment by arghyac35** [comment] 2021-04-07 15:06
> @arghyac35 can you make sure in package.lock that you are using the right version? 1.2.2-rc.0

Yes, I can see in noode_modules, that the version in 1.2.2-rc.0:
![image](https://user-images.githubusercontent.com/27964664/113889402-d364d000-97e0-11eb-9087-8b6098ad0153.png)

**Comment by paulbraam** [comment] 2021-04-09 08:33
Hi @lihaibh 
I also confirm that the error is still there.

**Comment by lihaibh** [comment] 2021-04-10 06:36
@paulbraam @arghyac35 
I mistakenly published to the wrong registry I had referenced in my computer.
Please try now with: `1.2.2-rc.2` thx.

**Comment by arghyac35** [comment] 2021-04-12 06:12
Still the same error.
I can confirm that my package is updated as you can see in yarn.lock:
![image](https://user-images.githubusercontent.com/27964664/114348460-2c878780-9b84-11eb-8634-c5e49ad37fb4.png)

**Comment by manorlh** [comment] 2021-05-04 15:34
also for me. , any news about that?

**Comment by lihaibh** [comment] 2021-05-04 16:26
@manorlh @arghyac35 there is a branch opened with the fix, but people report it still doesn't work for them, can someone help with the solution?
according to my local testing (i tried to modify collections during the backup) and it worked, so i dont understand why this solution doesn't work for others.

**Comment by sayka2** [comment] 2021-05-12 05:55
I was been using this awesome module for last 3 months in aws instance running node js and the same instance serving mongodb. I've done things like backing up data from that aws instance, restoring that tar file into my laptop localhost and reverse too. While doing such things, sometimes there will be a difference of more than 10,000 records, and added collections, deleted collections etc.. None of those changes were a problem, and I still get exact thing when restored.

Iam writing these so that @lihaibh can understand that the problem is not due to change in the collection.

I started facing this problem when I migrated db to atlas. While migrating, I created a db at atlas, and just added one empty collection. Then after that, I used this same module to restore all data from the file I backed up. The restore was clean and clear and easy. Awesome.. All collections and documents got migrated. But this error appeared when I tried to take a backup from there.

Conclusion.. This error is happening while trying to backup from atlas. Regardless of whether it was restored or manually loaded or just one empty collection

**Comment by sayka2** [comment] 2021-05-12 07:55
I'm not good at github. But I've tried pushing changes.

I just changed the tar-stream version to 2.0 and it is working good now.

**Comment by naizapp** [comment] 2021-05-17 14:06
I was so stuck in my current project because of this issue. So I left with no option other than to fix this for myself. After lots of debugging, finally found a solution. I have sent a pull request.

**Comment by lihaibh** [comment] 2021-05-24 03:44
im closing the current pull request as it looks like it works for some cases

**Comment by lihaibh** [comment] 2021-05-24 18:13
@naizapp @manorlh @arghyac35 @paulbraam @BradGamez @RusTorg 
I made more fixes and added more features, you are welcome to use the library at version `1.3.0`.
Sorry for the delay.
Enjoy and open an issue if you have one.
Thank you for your cooperation.

**Comment by lihaibh** [comment] 2021-05-27 15:01
Do you still have an issue?

**Comment by naizapp** [comment] 2021-05-28 23:02
@lihaibh  The current version from my temp forked branch is working smoothly now. I cannot risk disturbing it because it takes backup once daily. So I will start using the version 1.3.0 after two weeks for my project's beta update. Then I will give feedback for sure. Anyways thanks for this awesome library.

**Comment by lihaibh** [comment] 2021-05-29 14:58
We can add a new connector for S3, if you want to backup directly to S3 instead of locally.
Let me know if its a needed feature i will work on it.

**Comment by naizapp** [comment] 2021-06-06 09:12
My specific use case is downloading the mongo bkp from Atlas and images backup from S3. Having backup within S3 sounds very useful to others 👍🏻

**Comment by naizapp** [comment] 2021-06-06 09:14
![image](https://user-images.githubusercontent.com/16455658/120919131-a8f69c80-c6d5-11eb-8383-b4a986c3ad13.png)

**Comment by naizapp** [comment] 2021-06-06 09:17
![image](https://user-images.githubusercontent.com/16455658/120919227-16a2c880-c6d6-11eb-8eea-5e06a97f7edd.png)

**Comment by lihaibh** [comment] 2021-06-06 10:27
@naizapp you can change the `for await (const ...) {}` to `await transferer.promise()`

**Comment by peepopoggers** [comment] 2021-10-29 22:07
if anyone still has this issue, run `npm update` or `yarn update`, whatever you use.

**Comment by lihaibh** [comment] 2021-12-28 07:10
As i received no complaints about this error as i fixed it on the last pull request, this issue considered resolved.

**Closed by lihaibh** 2021-12-28 07:10 UTC
Labels: bug, help wanted
